create table if not exists public.productos (
    id bigint generated by default as identity primary key,
    nombre text not null check (char_length(nombre) between 1 and 160),
    categoria text not null check (char_length(categoria) between 1 and 100),
    precio numeric(10, 2) not null check (precio >= 0),
    descripcion text not null default '' check (char_length(descripcion) <= 2000),
    imagen_path text not null,
    creado_en timestamptz not null default now()
);

alter table public.productos enable row level security;

create policy "catalogo publico puede leer productos"
    on public.productos for select
    using (true);

create policy "admins autenticados pueden publicar productos"
    on public.productos for insert
    to authenticated
    with check (true);

create policy "admins autenticados pueden eliminar productos"
    on public.productos for delete
    to authenticated
    using (true);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

create policy "catalogo puede ver imagenes"
    on storage.objects for select
    using (bucket_id = 'product-images');

create policy "admins autenticados pueden subir imagenes"
    on storage.objects for insert
    to authenticated
    with check (bucket_id = 'product-images');

create policy "admins autenticados pueden eliminar imagenes"
    on storage.objects for delete
    to authenticated
    using (bucket_id = 'product-images');
